FROM debian:jessie

MAINTAINER tangf <316907331@qq.com>

RUN	apt-get update; \
	apt-get -y install g++ git subversion

RUN	mkdir /home/git; \
	cd /home/git; \
	git clone https://github.com/tang-f/201605.git ; 

